
GET http://localhost:8080/api/v1/flowers
###
GET http://localhost:8080/api/v1/users
###
GET http://localhost:8080/api/v1/users/email?email=hihi@gmail.com
### Test POST Add Flower
POST http://localhost:8080/api/v1/flowers
Content-Type: application/json

{
  "name": "Barabashka",
  "color": "Yellow",
  "price": 10.5,
  "available": true
}

###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "email": "haha@gmail.com",
  "dob" : "2006-05-07"
}
###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "email": "hihi@gmail.com",
  "dob" : "2008-03-07",
  "status" : "sended"
}